FROM nvcr.io/nvidia/cuda:12.3.1-devel-ubuntu22.04
RUN apt-get update && apt-get install -y python3-pip libgl1-mesa-glx libglib2.0-0 && pip install tensorflow[and-cuda] opencv-python matplotlib seaborn
WORKDIR /home
COPY ./docker_components /home
