FROM nvcr.io/nvidia/cuda:12.3.1-devel-ubuntu22.04
ARG BATCH_TO_COPY
RUN apt-get update
RUN apt-get install -y python3-pip
RUN pip install tensorflow[and-cuda] keras-cv
WORKDIR /home
COPY $BATCH_TO_COPY /home
ENTRYPOINT ["python3", "test_train.py"]